feat: update git scripts to use the new shell template functions

diff --git a/git/bin/git-edit b/git/bin/git-edit
--- a/git/bin/git-edit
+++ b/git/bin/git-edit
@@ -22,10 +22,17 @@
 #            .`                                 `/
 
 VERBOSE=0
+QUIET=0
+NOCOLOR=0
+NOLOG=1
+WARN_COUNT=0
+ERR_COUNT=0
+# FROM_STDIN=()
 
 NAME="$0"
 NAME="${NAME##*/}"
 NAME="${NAME##*-}"
+LOG="${NAME%%.*}.log"
 
 EDITOR="${EDITOR:-vim}"
 
@@ -33,6 +40,11 @@ SCRIPT_PATH="$0"
 WORKTREE=""
 
 SCRIPT_PATH="${SCRIPT_PATH%/*}"
+
+OS='unknown'
+ARCH="$(uname -m)"
+
+trap '{ exit_append; }' EXIT
 
 if hash realpath 2>/dev/null; then
     SCRIPT_PATH=$(realpath "$SCRIPT_PATH")
@@ -53,10 +65,144 @@ else
     fi
 fi
 
+if [ -z "$SHELL_PLATFORM" ]; then
+    if [[ -n $TRAVIS_OS_NAME ]]; then
+        export SHELL_PLATFORM="$TRAVIS_OS_NAME"
+    else
+        case "$OSTYPE" in
+            *'linux'*)    export SHELL_PLATFORM='linux' ;;
+            *'darwin'*)   export SHELL_PLATFORM='osx' ;;
+            *'freebsd'*)  export SHELL_PLATFORM='bsd' ;;
+            *'cygwin'*)   export SHELL_PLATFORM='cygwin' ;;
+            *'msys'*)     export SHELL_PLATFORM='msys' ;;
+            *'windows'*)  export SHELL_PLATFORM='windows' ;;
+            *)            export SHELL_PLATFORM='unknown' ;;
+        esac
+    fi
+fi
+
+case "$SHELL_PLATFORM" in
+    # TODO: support more linux distros
+    linux)
+        if [[ -f /etc/arch-release ]]; then
+            OS='arch'
+        elif [[ -f /etc/redhat-release ]] && [[ "$(cat /etc/redhat-release)" == Red\ Hat* ]]; then
+            OS='redhat'
+        elif [[ -f /etc/issue ]] && [[ "$(cat /etc/issue)" == Ubuntu* ]]; then
+            OS='ubuntu'
+        elif [[ -f /etc/debian_version ]] || [[ "$(cat /etc/issue)" == Debian* ]]; then
+            if [[ $ARCH =~ armv.* ]] || [[ $ARCH == aarch64 ]]; then
+                OS='raspbian'
+            else
+                OS='debian'
+            fi
+        fi
+        ;;
+    cygwin | msys | windows)
+        OS='windows'
+        ;;
+    osx)
+        OS='macos'
+        ;;
+    bsd)
+        OS='bsd'
+        ;;
+esac
+
+if ! hash is_windows 2>/dev/null; then
+    function is_windows() {
+        if [[ $SHELL_PLATFORM =~ (msys|cygwin|windows) ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_wls 2>/dev/null; then
+    function is_wls() {
+        if [[ "$(uname -r)" =~ Microsoft ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_osx 2>/dev/null; then
+    function is_osx() {
+        if [[ $SHELL_PLATFORM == 'osx' ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_root 2>/dev/null; then
+    function is_root() {
+        if ! is_windows && [[ $EUID -eq 0 ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash has_sudo 2>/dev/null; then
+    function has_sudo() {
+        if ! is_windows && hash sudo 2>/dev/null && [[ "$(groups)" =~ sudo ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_arm 2>/dev/null; then
+    function is_arm() {
+        local arch
+        arch="$(uname -m)"
+        if [[ $arch =~ ^arm ]] || [[ $arch =~ ^aarch ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_64bits 2>/dev/null; then
+    function is_64bits() {
+        local arch
+        arch="$(uname -m)"
+        if [[ $arch == 'x86_64' ]] || [[ $arch == 'arm64' ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+# colors
+# shellcheck disable=SC2034
+black="\033[0;30m"
+# shellcheck disable=SC2034
+red="\033[0;31m"
+# shellcheck disable=SC2034
+green="\033[0;32m"
+# shellcheck disable=SC2034
+yellow="\033[0;33m"
+# shellcheck disable=SC2034
+blue="\033[0;34m"
+# shellcheck disable=SC2034
+purple="\033[0;35m"
+# shellcheck disable=SC2034
+cyan="\033[0;36m"
+# shellcheck disable=SC2034
+white="\033[0;37;1m"
+# shellcheck disable=SC2034
+orange="\033[0;91m"
+# shellcheck disable=SC2034
+normal="\033[0m"
+# shellcheck disable=SC2034
+reset_color="\033[39m"
+
 function help_user() {
     cat <<EOF
-
-Description:
+Description
     Quick edit modified files in a git repo
 
 Usage:
@@ -68,64 +214,180 @@ Usage:
         $ git $NAME -e ed # uses ed editor
 
     Optional Flags
-        -e, --editor
-            Change the default editor
-                By default this uses \$EDITOR var and fallback vi in it's unset or empty
-
-        -h, --help
-            Display help, if you are seeing this, that means that you already know it (nice)
+        --nolog                 Disable log writing
+        --nocolor               Disable color output
+        -v, --verbose           Enable debug messages
+        -q, --quiet             Suppress all output but the errors
+        -e, --editor <EDITOR>   Change the default editor
+                                   By default this uses \$EDITOR var and fallback vi in it's unset or empty
+        -h, --help              Display this help message
 EOF
+}
+
+function warn_msg() {
+    local msg="$1"
+    if [[ $QUIET -eq 0 ]]; then
+        if [[ $NOCOLOR -eq 0 ]]; then
+            printf "${yellow}[!] Warning:${reset_color}\t %s\n" "$msg"
+        else
+            printf "[!] Warning:\t %s\n" "$msg"
+        fi
+    fi
+    WARN_COUNT=$((WARN_COUNT + 1))
+    if [[ $NOLOG -eq 0 ]]; then
+        printf "[!] Warning:\t %s\n" "$msg" >>"${LOG}"
+    fi
+    return 0
+}
+
+function error_msg() {
+    local msg="$1"
+    if [[ $NOCOLOR -eq 0 ]]; then
+        printf "${red}[X] Error:${reset_color}\t %s\n" "$msg" 1>&2
+    else
+        printf "[X] Error:\t %s\n" "$msg" 1>&2
+    fi
+    ERR_COUNT=$((ERR_COUNT + 1))
+    if [[ $NOLOG -eq 0 ]]; then
+        printf "[X] Error:\t %s\n" "$msg" >>"${LOG}"
+    fi
+    return 0
+}
+
+function status_msg() {
+    local msg="$1"
+    if [[ $QUIET -eq 0 ]]; then
+        if [[ $NOCOLOR -eq 0 ]]; then
+            printf "${green}[*] Info:${reset_color}\t %s\n" "$msg"
+        else
+            printf "[*] Info:\t %s\n" "$msg"
+        fi
+    fi
+    if [[ $NOLOG -eq 0 ]]; then
+        printf "[*] Info:\t\t %s\n" "$msg" >>"${LOG}"
+    fi
+    return 0
+}
+
+function verbose_msg() {
+    local msg="$1"
+    if [[ $VERBOSE -eq 1 ]]; then
+        if [[ $NOCOLOR -eq 0 ]]; then
+            printf "${purple}[+] Debug:${reset_color}\t %s\n" "$msg"
+        else
+            printf "[+] Debug:\t %s\n" "$msg"
+    fi
+    fi
+    if [[ $NOLOG -eq 0 ]]; then
+        printf "[+] Debug:\t\t %s\n" "$msg" >>"${LOG}"
+    fi
+    return 0
 }
 
 function __parse_args() {
     if [[ $# -lt 2 ]]; then
-        echo ""
+        error_msg "Internal error in __parse_args function trying to parse $1"
+        exit 1
     fi
 
-    local arg="$1"
-    local name="$2"
+    local flag="$2"
+    local value="$1"
 
-    local pattern="^--${name}[=][a-zA-Z0-9._-/~]+$"
+    local pattern="^--${flag}=[a-zA-Z0-9.:@_/~-]+$"
 
-    if [[ -n $3 ]]; then
-        local pattern="^--${name}[=]$3$"
+    if [[ -n $3   ]]; then
+        local pattern="^--${flag}=$3$"
     fi
 
-    if [[ $arg =~ $pattern ]]; then
-        local left_side="${arg#*=}"
+    if [[ $value =~ $pattern ]]; then
+        local left_side="${value#*=}"
         echo "${left_side/#\~/$HOME}"
     else
-        echo "$arg"
+        echo "$value"
     fi
 }
 
-function warn_msg() {
-    local warn_message="$1"
-    printf "[!]     ---- Warning!!! %s \n" "$warn_message"
+function initlog() {
+    if [[ $NOLOG -eq 0 ]]; then
+        [[ -n $LOG ]] && rm -f "${LOG}" 2>/dev/null
+        if ! touch "${LOG}" &>/dev/null; then
+            error_msg "Fail to init log file"
+            NOLOG=1
+            return 1
+        fi
+        if [[ -f "${SCRIPT_PATH}/shell/banner" ]]; then
+            cat "${SCRIPT_PATH}/shell/banner" >"${LOG}"
+        fi
+        if ! is_osx; then
+            LOG=$(readlink -e "${LOG}")
+        fi
+        verbose_msg "Using log at ${LOG}"
+    fi
+    return 0
 }
 
-function error_msg() {
-    local error_message="$1"
-    printf "[X]     ---- Error!!!   %s \n" "$error_message" 1>&2
+function exit_append() {
+    if [[ $NOLOG -eq 0 ]]; then
+        if [[ $WARN_COUNT -gt 0 ]] || [[ $ERR_COUNT -gt 0 ]]; then
+            printf "\n\n" >>"${LOG}"
+        fi
+
+        if [[ $WARN_COUNT -gt 0 ]]; then
+            printf "[*] Warnings:\t%s\n" "$WARN_COUNT" >>"${LOG}"
+        fi
+        if [[ $ERR_COUNT -gt 0 ]]; then
+            printf "[*] Errors:\t%s\n" "$ERR_COUNT" >>"${LOG}"
+        fi
+    fi
+    return 0
 }
 
-function status_msg() {
-    local status_message="$1"
-    printf "[*]     ---- %s \n" "$status_message"
+function raw_output() {
+    local msg="echo \"$1\""
+    if [[ $NOLOG -eq 0 ]]; then
+        msg="$msg | tee ${LOG}"
+    fi
+    if ! sh -c "$msg"; then
+            return 1
+    fi
+    return 0
 }
 
-function verbose_msg() {
+function shell_exec() {
+    local cmd="$1"
     if [[ $VERBOSE -eq 1 ]]; then
-        local debug_message="$1"
-        printf "[+]     ---- Debug!!!   %s \n" "$debug_message"
+        if [[ $NOLOG -eq 0 ]]; then
+            cmd="$cmd | tee ${LOG}"
+        fi
+        if ! sh -c "$cmd"; then
+            return 1
+        fi
+    elif [[ $NOLOG -eq 0 ]]; then
+        if ! sh -c "$cmd >> ${LOG}"; then
+            return 1
+        fi
+    else
+        if ! sh -c "$cmd &>/dev/null"; then
+            return 1
+        fi
     fi
+    return 0
 }
 
 while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-        --verbose)
+        --nolog)
+            NOLOG=1
+            ;;
+        --nocolor)
+            NOCOLOR=1
+            ;;
+        -v | --verbose)
             VERBOSE=1
+            ;;
+        -q | --quiet)
+            QUIET=1
             ;;
         -h | --help)
             help_user
@@ -143,6 +405,7 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
         *)
+            initlog
             error_msg "Unknown argument $key"
             help_user
             exit 1
@@ -150,6 +413,14 @@ while [[ $# -gt 0 ]]; do
     esac
     shift
 done
+
+initlog
+verbose_msg "Log Disable   : ${NOLOG}"
+verbose_msg "Current Shell : ${CURRENT_SHELL}"
+verbose_msg "Platform      : ${SHELL_PLATFORM}"
+verbose_msg "Architecture  : ${ARCH}"
+verbose_msg "OS            : ${OS}"
+
 
 # _GITDIR="$(git rev-parse --git-dir)"
 IFS=$'\n' read -r -d '' -a worklist < <(git worktree list 2>/dev/null | awk '{print $1}')
@@ -165,9 +436,15 @@ fi
 
 # shellcheck disable=SC2009,SC2046
 if [[ -n ${FILES[0]} ]]; then
+    verbose_msg "Files: ${FILES[*]}"
     "$EDITOR" "${FILES[@]}"
 else
     warn_msg "No files to edit"
+fi
+
+
+if [[ $ERR_COUNT -gt 0 ]]; then
+    exit 1
 fi
 
 exit 0
diff --git a/git/bin/git-pla b/git/bin/git-pla
--- a/git/bin/git-pla
+++ b/git/bin/git-pla
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC2317
 
 #
 #                              -`
@@ -22,6 +23,7 @@
 #            .`                                 `/
 
 VERBOSE=0
+QUIET=0
 NOCOLOR=0
 NOLOG=1
 WARN_COUNT=0
@@ -30,6 +32,7 @@ ERR_COUNT=0
 
 NAME="$0"
 NAME="${NAME##*/}"
+NAME="${NAME##*-}"
 LOG="${NAME%%.*}.log"
 
 SCRIPT_PATH="$0"
@@ -81,10 +84,12 @@ case "$SHELL_PLATFORM" in
     linux)
         if [[ -f /etc/arch-release ]]; then
             OS='arch'
-        elif [[ "$(cat /etc/issue)" == Ubuntu* ]]; then
+        elif [[ -f /etc/redhat-release ]] && [[ "$(cat /etc/redhat-release)" == Red\ Hat* ]]; then
+            OS='redhat'
+        elif [[ -f /etc/issue ]] && [[ "$(cat /etc/issue)" == Ubuntu* ]]; then
             OS='ubuntu'
         elif [[ -f /etc/debian_version ]] || [[ "$(cat /etc/issue)" == Debian* ]]; then
-            if [[ $ARCH == *\ armv7* ]]; then # Raspberry pi 3 uses armv7 cpu
+            if [[ $ARCH =~ armv.* ]] || [[ $ARCH == aarch64 ]]; then
                 OS='raspbian'
             else
                 OS='debian'
@@ -102,9 +107,67 @@ case "$SHELL_PLATFORM" in
         ;;
 esac
 
-if ! hash is_osx >/dev/null; then
+if ! hash is_windows 2>/dev/null; then
+    function is_windows() {
+        if [[ $SHELL_PLATFORM =~ (msys|cygwin|windows) ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_wls 2>/dev/null; then
+    function is_wls() {
+        if [[ "$(uname -r)" =~ Microsoft ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_osx 2>/dev/null; then
     function is_osx() {
         if [[ $SHELL_PLATFORM == 'osx' ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_root 2>/dev/null; then
+    function is_root() {
+        if ! is_windows && [[ $EUID -eq 0 ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash has_sudo 2>/dev/null; then
+    function has_sudo() {
+        if ! is_windows && hash sudo 2>/dev/null && [[ "$(groups)" =~ sudo ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_arm 2>/dev/null; then
+    function is_arm() {
+        local arch
+        arch="$(uname -m)"
+        if [[ $arch =~ ^arm ]] || [[ $arch =~ ^aarch ]]; then
+            return 0
+        fi
+        return 1
+    }
+fi
+
+if ! hash is_64bits 2>/dev/null; then
+    function is_64bits() {
+        local arch
+        arch="$(uname -m)"
+        if [[ $arch == 'x86_64' ]] || [[ $arch == 'arm64' ]]; then
             return 0
         fi
         return 1
@@ -144,66 +207,70 @@ Usage:
     $NAME [OPTIONAL]
 
     Optional Flags
-
         --nolog         Disable log writing
         --nocolor       Disable color output
         -v, --verbose   Enable debug messages
-        -h, --help      Display help, if you are seeing this, that means that you already know it (nice)
+        -q, --quiet     Suppress all output but the errors
+        -h, --help      Display this help message
 EOF
 }
 
 function warn_msg() {
-    local warn_message="$1"
+    local msg="$1"
+    if [[ $QUIET -eq 0 ]]; then
     if [[ $NOCOLOR -eq 0 ]]; then
-        printf "${yellow}[!] Warning:${reset_color}\t %s\n" "$warn_message"
+            printf "${yellow}[!] Warning:${reset_color}\t %s\n" "$msg"
     else
-        printf "[!] Warning:\t %s\n" "$warn_message"
+            printf "[!] Warning:\t %s\n" "$msg"
+    fi
     fi
     WARN_COUNT=$((WARN_COUNT + 1))
     if [[ $NOLOG -eq 0 ]]; then
-        printf "[!] Warning:\t %s\n" "$warn_message" >>"${LOG}"
+        printf "[!] Warning:\t %s\n" "$msg" >>"${LOG}"
     fi
     return 0
 }
 
 function error_msg() {
-    local error_message="$1"
+    local msg="$1"
     if [[ $NOCOLOR -eq 0 ]]; then
-        printf "${red}[X] Error:${reset_color}\t %s\n" "$error_message" 1>&2
+        printf "${red}[X] Error:${reset_color}\t %s\n" "$msg" 1>&2
     else
-        printf "[X] Error:\t %s\n" "$error_message" 1>&2
+        printf "[X] Error:\t %s\n" "$msg" 1>&2
     fi
     ERR_COUNT=$((ERR_COUNT + 1))
     if [[ $NOLOG -eq 0 ]]; then
-        printf "[X] Error:\t %s\n" "$error_message" >>"${LOG}"
+        printf "[X] Error:\t %s\n" "$msg" >>"${LOG}"
     fi
     return 0
 }
 
 function status_msg() {
-    local status_message="$1"
+    local msg="$1"
+    if [[ $QUIET -eq 0 ]]; then
     if [[ $NOCOLOR -eq 0 ]]; then
-        printf "${green}[*] Info:${reset_color}\t %s\n" "$status_message"
+            printf "${green}[*] Info:${reset_color}\t %s\n" "$msg"
     else
-        printf "[*] Info:\t %s\n" "$status_message"
+            printf "[*] Info:\t %s\n" "$msg"
+    fi
     fi
     if [[ $NOLOG -eq 0 ]]; then
-        printf "[*] Info:\t\t %s\n" "$status_message" >>"${LOG}"
+        printf "[*] Info:\t\t %s\n" "$msg" >>"${LOG}"
     fi
     return 0
 }
 
 function verbose_msg() {
-    local debug_message="$1"
+    local msg="$1"
     if [[ $VERBOSE -eq 1 ]]; then
         if [[ $NOCOLOR -eq 0 ]]; then
-            printf "${purple}[+] Debug:${reset_color}\t %s\n" "$debug_message"
+            printf "${purple}[+] Debug:${reset_color}\t %s\n" "$msg"
         else
-            printf "[+] Debug:\t %s\n" "$debug_message"
+            printf "[+] Debug:\t %s\n" "$msg"
         fi
     fi
     if [[ $NOLOG -eq 0 ]]; then
-        printf "[+] Debug:\t\t %s\n" "$debug_message" >>"${LOG}"
+        printf "[+] Debug:\t\t %s\n" "$msg" >>"${LOG}"
     fi
     return 0
 }
@@ -266,6 +333,38 @@ function exit_append() {
     return 0
 }
 
+function raw_output() {
+    local msg="echo \"$1\""
+    if [[ $NOLOG -eq 0 ]]; then
+        msg="$msg | tee ${LOG}"
+    fi
+    if ! sh -c "$msg"; then
+            return 1
+    fi
+    return 0
+}
+
+function shell_exec() {
+    local cmd="$1"
+    if [[ $VERBOSE -eq 1 ]]; then
+        if [[ $NOLOG -eq 0 ]]; then
+            cmd="$cmd | tee ${LOG}"
+        fi
+        if ! sh -c "$cmd"; then
+            return 1
+        fi
+    elif [[ $NOLOG -eq 0 ]]; then
+        if ! sh -c "$cmd >> ${LOG}"; then
+            return 1
+        fi
+    else
+        if ! sh -c "$cmd &>/dev/null"; then
+            return 1
+        fi
+    fi
+    return 0
+}
+
 while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -277,6 +376,9 @@ while [[ $# -gt 0 ]]; do
             ;;
         -v | --verbose)
             VERBOSE=1
+            ;;
+        -q | --quiet)
+            QUIET=1
             ;;
         -h | --help)
             help_user
@@ -305,16 +407,13 @@ verbose_msg "Platform      : ${SHELL_PLATFORM}"
 verbose_msg "Architecture  : ${ARCH}"
 verbose_msg "OS            : ${OS}"
 
-#######################################################################
-#                           CODE Goes Here                            #
-#######################################################################
 
 for i in *; do
     if [[ -d $i ]]; then
         if pushd "$i" &>/dev/null; then
             if git rev-parse --show-toplevel &>/dev/null; then
                 status_msg "Updating $i"
-                if ! git pull &>/dev/null; then
+                if ! shell_exec "git pull"; then
                     error_msg "Failed to update $i"
                 fi
             else
@@ -324,6 +423,7 @@ for i in *; do
         fi
     fi
 done
+
 
 if [[ $ERR_COUNT -gt 0 ]]; then
     exit 1
